language: php
script: phpunit -c tests/phpunit.xml.dist --verbose --coverage-text tests/

php:
  - 5.3.2

before_script:
  - "composer install -v"

after_script:
  - "phpunit -c tests/phpunit.xml.dist --testdox tests/"